export const RESOURCES_DATA = [
  {
    title: "Future",
    desc: "Future is the time or a period of time following the moment of speaking or writing; time regarded as still to come.",
    img: "https://picsum.photos/1920/1080",
    resUrl: "https://www.google.com/search?q=3d+printing",
  },
  {
    title: "Coding",
    desc: "Coding is the process of transforming ideas, solutions, and instructions into the language that the computer can understand – that is, binary-machine code. Coding is how humans are able to talk with computers.",
    img: "https://example.com/3d-printing-img.jpg",
    resUrl: "https://www.google.com/search?q=3d+printing",
  },
  {
    title: "Art",
    desc: "Art is the expression or application of human creative skill and imagination, typically in a visual form such as painting or sculpture, producing works to be appreciated primarily for their beauty or emotional power.",
    img: "https://example.com/3d-printing-img.jpg",
    resUrl: "https://www.google.com/search?q=3d+printing",
  },
  {
    title: "3D Printing",
    desc: "3D printing is a process of creating three-dimensional objects from a digital file by layering materials on top of each other. It has applications in various fields including manufacturing, medicine, architecture, and more.",
    img: "https://example.com/3d-printing-img.jpg",
    resUrl: "https://www.google.com/search?q=3d+printing",
  },
  {
    title: "Virtual Reality (VR)",
    desc: "Virtual Reality (VR) is a technology that creates a simulated environment or experience. Users can interact with and explore this artificial environment using special equipment such as VR headsets.",
    img: "https://example.com/virtual-reality-img.jpg",
    resUrl: "https://www.google.com/search?q=virtual+reality",
  },
  {
    title: "Augmented Reality (AR)",
    desc: "Augmented Reality (VR) is an interactive technology that overlays virtual elements onto the real world, enhancing the user's perception and interaction with their environment.",
    img: "https://example.com/virtual-reality-img.jpg",
    resUrl: "https://www.google.com/search?q=virtual+reality",
  },
  {
    title: "Artificial Intelligence (AI)",
    desc: "Artificial Intelligence (AI) is a branch of computer science that focuses on creating intelligent machines capable of performing tasks that typically require human intelligence.",
    img: "https://example.com/ai-img.jpg",
    resUrl: "https://www.google.com/search?q=artificial+intelligence",
  },
  {
    title: "Architecture",
    desc: "Architecture is the art and science of designing and constructing buildings and other physical structures. It involves creative and technical skills to create functional, aesthetically pleasing spaces.",
    img: "https://example.com/architecture-img.jpg",
    resUrl: "https://www.google.com/search?q=architecture",
  },
  {
    title: "Engineering",
    desc: "Engineering is the creative application of science, mathematical methods, and empirical evidence to the innovation, design, construction, and maintenance of structures, machines, materials, devices, systems, processes, and organizations.",
    img: "https://example.com/industrial-automation-img.jpg",
    resUrl: "https://www.google.com/search?q=industrial+automation",
  },
  {
    title: "Web Development",
    desc: "Web development is the building and maintenance of websites; it's the work that happens behind the scenes to make a website look great, work fast and perform well with a seamless user experience. Web developers, or 'devs', do this by using a variety of coding languages.",
    img: "https://example.com/industrial-automation-img.jpg",
    resUrl: "https://www.google.com/search?q=industrial+automation",
  },
  {
    title: "Industrial Automation",
    desc: "Industrial automation involves the use of technology and control systems to automate industrial processes. It aims to improve efficiency, productivity, and safety by replacing manual labor with machines and robots.",
    img: "https://example.com/industrial-automation-img.jpg",
    resUrl: "https://www.google.com/search?q=industrial+automation",
  },
  {
    title: "Photography",
    desc: "Photography is the art and practice of capturing imgs using light. It involves various techniques, equipment, and creative skills to produce visually compelling photographs.",
    img: "https://example.com/photography-img.jpg",
    resUrl: "https://www.google.com/search?q=photography",
  },
  {
    title: "Robotics",
    desc: "Robotics is the interdisciplinary field of science and engineering that involves the design, construction, operation, and programming of robots. It combines aspects of mechanical engineering, electrical engineering, and computer science.",
    img: "https://example.com/robotics-img.jpg",
    resUrl: "https://www.google.com/search?q=robotics",
  },
  {
    title: "App Development for Social Impact",
    desc: "App development for social impact involves creating mobile applications that address social and environmental challenges. It aims to leverage technology to make a positive difference in communities and promote social change.",
    img: "https://example.com/social-impact-app-development-img.jpg",
    resUrl: "https://www.google.com/search?q=app+development+for+social+impact",
  },
  {
    title: "Neuroscience",
    desc: "Neuroscience is the study of the nervous system, including the brain, spinal cord, and peripheral nerves. It explores the structure, function, and development of the nervous system and its impact on behavior, cognition, and health.",
    img: "https://example.com/neuroscience-img.jpg",
    resUrl: "https://www.google.com/search?q=neuroscience",
  },
  {
    title: "Forensic Science",
    desc: "Forensic science applies scientific techniques to investigate crimes and analyze evidence. It involves disciplines such as DNA analysis, fingerprinting, ballistics, and crime scene investigation to support legal investigations.",
    img: "https://example.com/forensic-science-img.jpg",
    resUrl: "https://www.google.com/search?q=forensic+science",
  },
  {
    title: "Game Development",
    desc: "Game Development involves the creation and production of video games. It includes designing gameplay, creating characters, developing graphics and audio, and programming game mechanics.",
    img: "https://example.com/game-development-img.jpg",
    resUrl: "https://www.google.com/search?q=game+development",
  },
  {
    title: "Fashion Design",
    desc: "Fashion Design is the art and application of designing clothing and accessories. It involves creativity, research, and technical skills to create garments that are visually appealing and functional.",
    img: "https://example.com/fashion-design-img.jpg",
    resUrl: "https://www.google.com/search?q=fashion+design",
  },
  {
    title: "Music Production",
    desc: "Music Production involves the creation, recording, and editing of music. It includes composing, arranging, mixing, and mastering audio tracks using various equipment and software.",
    img: "https://example.com/music-production-img.jpg",
    resUrl: "https://www.google.com/search?q=music+production",
  },
  {
    title: "Music Technology",
    desc: "Music technology involves the use of technology to create, produce, and manipulate sound for musical purposes, including electronic music and audio recording techniques.",
    img: "https://example.com/music-production-img.jpg",
    resUrl: "https://www.google.com/search?q=music+production",
  },

  {
    title: "Computational Art",
    desc: "Computational art involves the use of computer algorithms, programming, and digital tools to create visual and interactive artworks.",
    img: "https://example.com/graphic-design-img.jpg",
    resUrl: "https://www.google.com/search?q=graphic+design",
  },
  {
    title: "Mobile App Development",
    desc: "Mobile app development involves creating applications for mobile devices such as smartphones and tablets. It requires skills in programming languages and frameworks to design and build user-friendly and functional apps.",
    img: "https://example.com/mobile-app-development-img.jpg",
    resUrl: "https://www.google.com/search?q=mobile+app+development",
  },
  {
    title: "Graphic Design",
    desc: "Graphic Design is the art of visual communication that combines imgs, typography, and other visual elements to convey messages. It involves using design software and creative skills to create visual compositions.",
    img: "https://example.com/graphic-design-img.jpg",
    resUrl: "https://www.google.com/search?q=graphic+design",
  },
  {
    title: "Data Visualization",
    desc: "Data Visualization is the graphical representation of data and information. It involves creating visual elements such as charts, graphs, and infographics to help people understand complex data sets.",
    img: "https://example.com/data-visualization-img.jpg",
    resUrl: "https://www.google.com/search?q=data+visualization",
  },
  {
    title: "Blockchain ",
    desc: "A blockchain is a decentralized, distributed and public digital ledger that is used to record transactions across many computers so that the record cannot be altered retroactively without the alteration of all subsequent blocks and the consensus of the network.",
    img: "https://example.com/sculpture-img.jpg",
    resUrl: "https://www.google.com/search?q=sculpture",
  },
  {
    title: "Metaverse ",
    desc: "Metaverse refers to an immersive and persistent three-dimensional virtual realm, shared with many users, that spans various digital platforms and merges with the physical world, where people can shop, work, play and hang out together in real time.",
    img: "https://example.com/sculpture-img.jpg",
    resUrl: "https://www.google.com/search?q=sculpture",
  },
  {
    title: "Network",
    desc: "Network is a group of two or more computers or other electronic devices that are interconnected for the purpose of exchanging data and sharing resources.",
    img: "https://example.com/sculpture-img.jpg",
    resUrl: "https://www.google.com/search?q=sculpture",
  },
  {
    title: "Sculpture",
    desc: "Sculpture is the art of creating three-dimensional objects by shaping or combining materials such as clay, wood, metal, or stone. It involves various techniques and skills to bring ideas into physical form.",
    img: "https://example.com/sculpture-img.jpg",
    resUrl: "https://www.google.com/search?q=sculpture",
  },
  {
    title: "Environmental Design",
    desc: "Environmental design focuses on creating sustainable and aesthetically pleasing environments, encompassing architecture, urban planning, and landscape design.",
    img: "https://example.com/environmental-science-img.jpg",
    resUrl: "https://www.google.com/search?q=environmental+science",
  },
  {
    title: "Environmental Science",
    desc: "Environmental Science is the study of the environment and its interactions with living organisms. It involves understanding ecological systems, environmental issues, and finding sustainable solutions.",
    img: "https://example.com/environmental-science-img.jpg",
    resUrl: "https://www.google.com/search?q=environmental+science",
  },
  {
    title: "Community Architecture",
    desc: "Community architecture is a practice that contributes to creating awareness in society, involving the users in its design process, and making them differentiate between their needs and aspirations. This process gives the users the authority to claim their environment around them, as they play a vital role in designing.",
    img: "https://example.com/sustainable-architecture-img.jpg",
    resUrl: "https://www.google.com/search?q=sustainable+architecture",
  },
  {
    title: "Sustainable Architecture",
    desc: "Sustainable architecture focuses on designing buildings and structures that minimize environmental impact and promote energy efficiency. It combines innovative design techniques and sustainable materials to create eco-friendly spaces.",
    img: "https://example.com/sustainable-architecture-img.jpg",
    resUrl: "https://www.google.com/search?q=sustainable+architecture",
  },
  {
    title: "Film Production",
    desc: "Film Production involves the creation and production of films. It includes screenwriting, directing, cinematography, editing, and post-production processes to bring stories to life on the screen.",
    img: "https://example.com/film-production-img.jpg",
    resUrl: "https://www.google.com/search?q=film+production",
  },
  {
    title: "Biotechnology",
    desc: "Biotechnology is the application of biological processes, organisms, or systems to develop or create products. It involves using living organisms or their components in various fields such as medicine, agriculture, and industrial manufacturing.",
    img: "https://example.com/biotechnology-img.jpg",
    resUrl: "https://www.google.com/search?q=biotechnology",
  },
  {
    title: "Biomedical Engineering",
    desc: "Biomedical engineering combines principles of engineering and biology to develop innovative solutions for healthcare. It involves designing medical devices, prosthetics, and advanced imaging systems to improve patient care.",
    img: "https://example.com/biomedical-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=biomedical+engineering",
  },
  {
    title: "Astrophysics",
    desc: "Astrophysics is the branch of physics that deals with the study of celestial objects, their properties, and the universe as a whole. It involves understanding the behavior of stars, galaxies, black holes, and other cosmic phenomena.",
    img: "https://example.com/astrophysics-img.jpg",
    resUrl: "https://www.google.com/search?q=astrophysics",
  },
  {
    title: "Animation",
    desc: "Animation is the process of creating moving imgs using a sequence of static visual elements. It involves techniques such as 2D or 3D computer animation, stop motion, or traditional hand-drawn animation.",
    img: "https://example.com/animation-img.jpg",
    resUrl: "https://www.google.com/search?q=animation",
  },
  {
    title: "Computer Animation",
    desc: "Computer animation involves creating animated visual content using digital tools and software. It combines artistry, storytelling, and technical skills to bring characters and objects to life in movies, video games, and other media.",
    img: "https://example.com/computer-animation-img.jpg",
    resUrl: "https://www.google.com/search?q=computer+animation",
  },
  {
    title: "Renewable Energy",
    desc: "Renewable energy refers to energy sources that can be replenished naturally, such as solar power, wind power, hydroelectricity, and geothermal energy. It plays a crucial role in mitigating climate change and reducing dependence on fossil fuels.",
    img: "https://example.com/renewable-energy-img.jpg",
    resUrl: "https://www.google.com/search?q=renewable+energy",
  },
  {
    title: "Environmental Conservation",
    desc: "Environmental conservation focuses on protecting and preserving natural resources and ecosystems. It involves efforts to reduce pollution, promote sustainable practices, and raise awareness about environmental issues.",
    img: "https://example.com/environmental-conservation-img.jpg",
    resUrl: "https://www.google.com/search?q=environmental+conservation",
  },
  {
    title: "Robotics Engineering",
    desc: "Robotics engineering focuses on designing, building, and programming robots to perform tasks autonomously or assist humans in various industries and applications.",
    img: "https://example.com/chemical-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=chemical+engineering",
  },
  {
    title: "Chemical Engineering",
    desc: "Chemical Engineering is the branch of engineering that deals with the design and operation of chemical processes. It involves applying principles of chemistry, physics, and mathematics to convert raw materials into valuable products.",
    img: "https://example.com/chemical-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=chemical+engineering",
  },
  {
    title: "Electrical Engineering",
    desc: "Electrical Engineering is the branch of engineering that deals with the study and application of electricity, electronics, and electromagnetism. It involves designing, developing, and maintaining electrical systems and devices.",
    img: "https://example.com/electrical-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=electrical+engineering",
  },
  {
    title: "Astronomy",
    desc: "Astronomy is the scientific study of celestial objects, such as stars, planets, galaxies, and the universe as a whole. It involves observation, theoretical modeling, and understanding the origins and evolution of these objects.",
    img: "https://example.com/astronomy-img.jpg",
    resUrl: "https://www.google.com/search?q=astronomy",
  },
  {
    title: "Civil Engineering",
    desc: "Civil Engineering is the branch of engineering that deals with the design, construction, and maintenance of infrastructure projects. It involves planning and building structures such as bridges, roads, buildings, and dams.",
    img: "https://example.com/civil-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=civil+engineering",
  },
  {
    title: "Mechanical Engineering",
    desc: "Mechanical Engineering is the branch of engineering that deals with the design, analysis, and manufacturing of mechanical systems. It involves applying principles of physics and materials science to create mechanical devices and machinery.",
    img: "https://example.com/mechanical-engineering-img.jpg",
    resUrl: "https://www.google.com/search?q=mechanical+engineering",
  },
  {
    title: "Industrial Design",
    desc: "Industrial Design is the process of designing and creating products that are aesthetically pleasing, functional, and user-friendly. It involves considering the form, function, and manufacturing processes of the product.",
    img: "https://example.com/industrial-design-img.jpg",
    resUrl: "https://www.google.com/search?q=industrial+design",
  },
  {
    title: "Environmental Science",
    desc: "Environmental Science is the study of the environment and its interactions with living organisms. It involves understanding ecological systems, environmental issues, and finding sustainable solutions.",
    img: "https://example.com/environmental-science-img.jpg",
    resUrl: "https://www.google.com/search?q=environmental+science",
  },
  {
    title: "Film Production",
    desc: "Film Production involves the creation and production of films. It includes screenwriting, directing, cinematography, editing, and post-production processes to bring stories to life on the screen.",
    img: "https://example.com/film-production-img.jpg",
    resUrl: "https://www.google.com/search?q=film+production",
  },
  {
    title: "Digital Fabrication",
    desc: " Digital fabrication refers to the process of creating physical objects using digital design tools, computer-controlled machines, and additive or subtractive manufacturing techniques.",
    img: "https://example.com/film-production-img.jpg",
    resUrl: "https://www.google.com/search?q=film+production",
  },
  {
    title: "Cybersecurity",
    desc: "Cybersecurity focuses on protecting computer systems, networks, and data from unauthorized access, attacks, and breaches. It involves measures such as encryption, secure coding practices, and network monitoring.",
    img: "https://example.com/cybersecurity-img.jpg",
    resUrl: "https://www.google.com/search?q=cybersecurity",
  },
  {
    title: "Astronomy",
    desc: "Astronomy is the scientific study of celestial objects, such as stars, planets, galaxies, and the universe as a whole. It involves observations, theoretical models, and exploration to understand the mysteries of space.",
    img: "https://example.com/astronomy-img.jpg",
    resUrl: "https://www.google.com/search?q=astronomy",
  },
  {
    title: "Mathematics",
    desc: "Mathematics is the study of numbers, quantities, and shapes, as well as the relationships between them. It is a fundamental field of STEM that plays a role in various scientific and technological applications.",
    img: "https://example.com/mathematics-img.jpg",
    resUrl: "https://www.google.com/search?q=mathematics",
  },
  {
    title: "Physics",
    desc: "Physics is the scientific study of matter, energy, and their interactions. It explores the fundamental principles that govern the universe, from the smallest particles to the vastness of space.",
    img: "https://example.com/physics-img.jpg",
    resUrl: "https://www.google.com/search?q=physics",
  },
  {
    title: "Chemistry",
    desc: "Chemistry is the study of matter, its properties, composition, and interactions. It investigates the building blocks of substances and their transformations, providing a foundation for understanding materials and chemical reactions.",
    img: "https://example.com/chemistry-img.jpg",
    resUrl: "https://www.google.com/search?q=chemistry",
  },
  {
    title: "Biology",
    desc: "Biology is the study of living organisms, including their structure, function, growth, evolution, and distribution. It encompasses various subfields such as genetics, ecology, and molecular biology.",
    img: "https://example.com/biology-img.jpg",
    resUrl: "https://www.google.com/search?q=biology",
  },
  {
    title: "Electronics",
    desc: "Electronics is the branch of physics and engineering that deals with the behavior and control of electrons and their application in devices and systems. It involves the study of circuits, semiconductors, and electronic components.",
    img: "https://example.com/electronics-img.jpg",
    resUrl: "https://www.google.com/search?q=electronics",
  },
  {
    title: "Genetics",
    desc: "Genetics isthe study of genes, heredity, and variation in living organisms. It explores how traits are passed from one generation to another and how genetic information can be manipulated to understand and address genetic diseases.",
    img: "https://example.com/genetics-img.jpg",
    resUrl: "https://www.google.com/search?q=genetics",
  },
  {
    title: "Meteorology",
    desc: "Meteorology is the scientific study of the Earth's atmosphere, weather patterns, and climate. It involves the observation and analysis of atmospheric conditions to predict and understand weather phenomena.",
    img: "https://example.com/meteorology-img.jpg",
    resUrl: "https://www.google.com/search?q=meteorology",
  },
  {
    title: "Geology",
    desc: "Geology is the study of the Earth's solid materials, including rocks, minerals, and the processes that shape the planet's structure and history. It investigates the formation of rocks, fossils, and geological phenomena.",
    img: "https://example.com/geology-img.jpg",
    resUrl: "https://www.google.com/search?q=geology",
  },
  {
    title: "Computer Science",
    desc: "Computer science is the study of computation, algorithms, and information processing. It involves programming, data structures, algorithms, and the theoretical foundations of computing.",
    img: "https://example.com/computer-science-img.jpg",
    resUrl: "https://www.google.com/search?q=computer+science",
  },
  {
    title: "Mathematical Modeling",
    desc: "Mathematical modeling involves using mathematical equations and algorithms to represent and analyze real-world phenomena. It allows scientists and engineers to make predictions, solve problems, and optimize processes.",
    img: "https://example.com/mathematical-modeling-img.jpg",
    resUrl: "https://www.google.com/search?q=mathematical+modeling",
  },
  {
    title: "Nanotechnology",
    desc: "Nanotechnology is the science, engineering, and application of materials and devices at the nanometer scale. It involves manipulating and controlling matter at the atomic and molecular levels to create new functionalities.",
    img: "https://example.com/nanotechnology-img.jpg",
    resUrl: "https://www.google.com/search?q=nanotechnology",
  },
  {
    title: "Space Exploration",
    desc: "Space exploration involves the discovery and exploration of celestial bodies beyond Earth. It encompasses missions to planets, moons, asteroids, and other cosmic objects to expand our knowledge of the universe.",
    img: "https://example.com/space-exploration-img.jpg",
    resUrl: "https://www.google.com/search?q=space+exploration",
  },
  {
    title: "Ecology",
    desc: "Ecology is the scientific study of the relationships between living organisms and their environment. It explores how organisms interact with each other and their surroundings, including ecosystems and biodiversity.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Hydroponics ",
    desc: "Hydroponics is the technique of growing plants using a water-based nutrient solution rather than soil, and can include an aggregate substrate, or growing media, such as vermiculite, coconut coir, or perlite.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Biophilia  ",
    desc: "Biophilia a hypothetical human tendency to interact or be closely associated with other forms of life in nature : a desire or tendency to commune with nature.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Metaphysical   ",
    desc: "Metaphysical is the nature and origin of reality itself, the immortal soul, and the existence of a supreme being.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Software Engineering    ",
    desc: "Software engineering is the process of developing, testing and deploying computer applications to solve real-world problems by adhering to a set of engineering principles and best practices.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Self-Sufficient    ",
    desc: "Self-Sufficient is needing no outside help in satisfying one's basic needs, especially with regard to the production of food.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Community     ",
    desc: "Community is a group of people with a common characteristic or interest living together within a larger society.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Financial Literacy     ",
    desc: "Financial literacy is the ability to understand and effectively use various financial skills, including personal financial management, budgeting, and investing. When you are financially literate, you have the foundation of a relationship with money, and it is a lifelong journey of learning.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Pan-Africanism     ",
    desc: "Pan-Africanism is the brotherhood and collaboration among all people of African descent whether they lived inside or outside of Africa.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Philosophy    ",
    desc: "Philosophy is the study of the basic ideas about knowledge, truth, right and wrong, religion, and the nature and meaning of life.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Future Mindset    ",
    desc: "Future Minded is a mindset that balances optimistic action with thoughtful pragmatism in order to imagine and envision possible futures. It is a form of preparation to ready ourselves for what comes next.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Freethinker   ",
    desc: "Freethinker a person who forms opinions on the basis of reason, independent of authority or tradition, especially a person whose religious opinions differ from established belief.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Meditation    ",
    desc: "Meditation is a practice that involves focusing or clearing your mind using a combination of mental and physical techniques. ",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Social Networks    ",
    desc: "Social networks are websites and apps that allow users and organizations to connect, communicate, share information and form relationships. People can connect with others in the same area, families, friends, and those with the same interests.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Montessori    ",
    desc: "Montessori a system of education for young children that seeks to develop natural interests and activities rather than use formal teaching methods.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Atmospheric Water Generator    ",
    desc: "Atmospheric water generation (AWG) uses technology to produce potable water from surrounding air. ",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Family Bank    ",
    desc: "Family bank—a family-funded entity that offers financing only to family members or family-owned assets—is a mechanism for achieving those goals.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Solar Power   ",
    desc: "Solar energy is radiant light and heat from the Sun that is harnessed using a range of technologies such as solar power to generate electricity, solar thermal energy, and solar architecture.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
  {
    title: "Energy   ",
    desc: "Energy is the ability to do work.",
    img: "https://example.com/ecology-img.jpg",
    resUrl: "https://www.google.com/search?q=ecology",
  },
];
